[env:esp32cam]
platform = espressif32@6.5.0
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    https://github.com/tzapu/WiFiManager.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    yoursunny/esp32cam @ ^0.0.20240110
    ayushsharma82/ElegantOTA @ ^3.1.6

lib_ignore =
    AsyncTCP_RP2040W

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DESP32CAM_ASYNCWEB
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
