[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    https://github.com/tzapu/WiFiManager.git
    ESP Async WebServer
    https://github.com/me-no-dev/AsyncTCP.git
    yoursunny/esp32cam @ ^0.0.20240110

lib_ignore =
    AsyncTCP_RP2040W

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DESP32CAM_ASYNCWEB

